2023-02-09 21:14:48,849 DEBUG   MainThread:915119 [wandb_config.py:_load_defaults():119] no defaults not found in config-defaults.yaml
2023-02-09 21:14:48,855 DEBUG   MainThread:915119 [meta.py:setup():97] code probe starting
2023-02-09 21:14:48,862 DEBUG   MainThread:915119 [git_repo.py:repo():30] git repository is invalid
2023-02-09 21:14:48,862 DEBUG   MainThread:915119 [meta.py:_setup_code_program():58] save program starting
2023-02-09 21:14:48,863 DEBUG   MainThread:915119 [meta.py:_setup_code_program():60] save program starting: /scratch/trafficdriving/carla_project/src/traffic_map_model.py
2023-02-09 21:14:48,863 DEBUG   MainThread:915119 [meta.py:_setup_code_program():65] save program saved: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/code/carla_project/src/traffic_map_model.py
2023-02-09 21:14:48,864 DEBUG   MainThread:915119 [meta.py:_setup_code_program():67] save program
2023-02-09 21:14:48,864 DEBUG   MainThread:915119 [meta.py:setup():119] code probe done
2023-02-09 21:14:48,908 DEBUG   MainThread:915119 [run_manager.py:__init__():541] Initialized sync for ppo_mapmodel/test_ppo2
2023-02-09 21:14:48,914 INFO    MainThread:915119 [run_manager.py:wrap_existing_process():1144] wrapping existing process 915047
2023-02-09 21:14:48,914 WARNING MainThread:915119 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2023-02-09 21:14:48,917 DEBUG   MainThread:915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): pypi.org:443
2023-02-09 21:14:48,955 DEBUG   MainThread:915119 [connectionpool.py:_make_request():456] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 74008
2023-02-09 21:14:48,972 INFO    MainThread:915119 [run_manager.py:init_run():924] system metrics and metadata threads started
2023-02-09 21:14:48,972 INFO    MainThread:915119 [run_manager.py:init_run():933] checking resume status, waiting at most 10 seconds
2023-02-09 21:14:48,978 DEBUG   Thread-14 :915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): api.wandb.ai:443
2023-02-09 21:14:49,058 DEBUG   Thread-14 :915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 927
2023-02-09 21:14:49,062 INFO    MainThread:915119 [run_manager.py:init_run():951] resuming run from id: UnVuOnYxOnRlc3RfcHBvMjpwcG9fbWFwbW9kZWw6bGF1cmF5dXpoZW5n
2023-02-09 21:14:49,071 INFO    MainThread:915119 [run_manager.py:init_run():963] upserting run before process can begin, waiting at most 10 seconds
2023-02-09 21:14:49,080 DEBUG   Thread-17 :915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): api.wandb.ai:443
2023-02-09 21:14:49,169 DEBUG   Thread-17 :915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 515
2023-02-09 21:14:49,175 INFO    Thread-17 :915119 [run_manager.py:_upsert_run():1048] saving patches
2023-02-09 21:14:49,175 INFO    Thread-17 :915119 [run_manager.py:_upsert_run():1052] saving pip packages
2023-02-09 21:14:49,176 INFO    Thread-17 :915119 [run_manager.py:_upsert_run():1054] initializing streaming files api
2023-02-09 21:14:49,177 INFO    Thread-17 :915119 [run_manager.py:_upsert_run():1061] unblocking file change observer, beginning sync with W&B servers
2023-02-09 21:14:49,178 INFO    MainThread:915119 [run_manager.py:wrap_existing_process():1161] informing user process we are ready to proceed
2023-02-09 21:14:49,182 DEBUG   Thread-18 :915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): api.wandb.ai:443
2023-02-09 21:14:49,183 INFO    MainThread:915119 [run_manager.py:_sync_etc():1268] entering loop for messages from user process
2023-02-09 21:14:49,205 INFO    MainThread:915119 [run_manager.py:_sync_etc():1291] received message from user process: {"exitcode": 1}
2023-02-09 21:14:49,206 INFO    MainThread:915119 [run_manager.py:_sync_etc():1377] closing log streams and sending exitcode to W&B
2023-02-09 21:14:49,207 INFO    MainThread:915119 [run_manager.py:shutdown():1068] shutting down system stats and metadata service
2023-02-09 21:14:49,250 DEBUG   Thread-18 :915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 47
2023-02-09 21:14:49,854 INFO    Thread-3  :915119 [run_manager.py:_on_file_modified():688] file/dir modified: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/config.yaml
2023-02-09 21:14:49,872 DEBUG   Thread-3  :915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): api.wandb.ai:443
2023-02-09 21:14:49,962 DEBUG   Thread-3  :915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 514
2023-02-09 21:14:49,965 INFO    Thread-3  :915119 [run_manager.py:_on_file_modified():688] file/dir modified: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/wandb-history.jsonl
2023-02-09 21:14:49,966 INFO    Thread-3  :915119 [run_manager.py:_on_file_created():677] file/dir created: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/wandb-summary.json
2023-02-09 21:14:49,966 INFO    Thread-3  :915119 [run_manager.py:_on_file_created():677] file/dir created: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/output.log
2023-02-09 21:14:49,967 INFO    Thread-3  :915119 [run_manager.py:_on_file_created():677] file/dir created: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/wandb-events.jsonl
2023-02-09 21:14:49,967 ERROR   Thread-3  :915119 [run_manager.py:on_created():318] Streaming file created twice in same run: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/wandb-events.jsonl
2023-02-09 21:14:49,967 INFO    Thread-3  :915119 [run_manager.py:_on_file_created():677] file/dir created: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/requirements.txt
2023-02-09 21:14:49,968 INFO    Thread-3  :915119 [run_manager.py:_on_file_created():677] file/dir created: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/wandb-metadata.json
2023-02-09 21:14:49,969 INFO    Thread-3  :915119 [run_manager.py:_on_file_created():677] file/dir created: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/code
2023-02-09 21:14:49,974 INFO    MainThread:915119 [run_manager.py:shutdown():1080] stopping streaming files and file change observer
2023-02-09 21:14:50,853 INFO    Thread-3  :915119 [run_manager.py:_on_file_modified():688] file/dir modified: /scratch/trafficdriving/results/phase1/test_ppo2/wandb/run-20230210_021448-test_ppo2/wandb-metadata.json
2023-02-09 21:14:51,092 DEBUG   MainThread:915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): api.wandb.ai:443
2023-02-09 21:14:51,183 DEBUG   MainThread:915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 521
2023-02-09 21:14:51,189 DEBUG   Thread-7  :915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): api.wandb.ai:443
2023-02-09 21:14:51,201 DEBUG   Thread-19 :915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): api.wandb.ai:443
2023-02-09 21:14:51,272 DEBUG   Thread-19 :915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 584
2023-02-09 21:14:51,279 DEBUG   Thread-19 :915119 [connectionpool.py:_new_conn():1003] Starting new HTTPS connection (1): storage.googleapis.com:443
2023-02-09 21:14:51,289 DEBUG   Thread-7  :915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /files/laurayuzheng/ppo_mapmodel/test_ppo2/file_stream HTTP/1.1" 200 181
2023-02-09 21:14:51,359 DEBUG   Thread-7  :915119 [connectionpool.py:_make_request():456] https://api.wandb.ai:443 "POST /files/laurayuzheng/ppo_mapmodel/test_ppo2/file_stream HTTP/1.1" 200 181
2023-02-09 21:14:51,360 INFO    MainThread:915119 [run_manager.py:_sync_etc():1389] process only ran for 2 seconds, not syncing files
2023-02-09 21:14:51,360 INFO    MainThread:915119 [test_ppo2:run_manager.py:_sync_etc():1389] process only ran for 2 seconds, not syncing files
