[34m[1mwandb[0m: [32m[41mERROR[0m Attempted to change value of key "save_dir" from checkpoints/test_ppo to results/phase1/test_ppo
[34m[1mwandb[0m: [32m[41mERROR[0m If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/trafficdriving/carla_project/src/traffic_map_model.py", line 290, in <module>
    main(parsed)
  File "/scratch/trafficdriving/carla_project/src/traffic_map_model.py", line 259, in main
    trainer.fit(model)
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 602, in fit
    self.single_gpu_train(model)
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 470, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 748, in run_pretrain_routine
    self.logger.log_hyperparams(ref_model.hparams)
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 18, in wrapped_fn
    fn(self, *args, **kwargs)
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 96, in log_hyperparams
    self.experiment.config.update(params)
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/wandb/wandb_config.py", line 298, in update
    self._update(params,
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/wandb/wandb_config.py", line 291, in _update
    key, val = self._sanitize(key, val, allow_val_change=allow_val_change or as_defaults)
  File "/home/laura/anaconda3/envs/icra23/lib/python3.8/site-packages/wandb/wandb_config.py", line 229, in _sanitize
    raise ConfigError('Attempted to change value of key "{}" from {} to {}\nIf you really want to do this, pass allow_val_change=True to config.update()'.format(
wandb.wandb_config.ConfigError: Attempted to change value of key